# Generated by Django 3.0.5 on 2020-12-02 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20201202_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.Product'),
            preserve_default=False,
        ),
    ]
