# Generated by Django 3.0.5 on 2020-12-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
