# Generated by Django 3.0.5 on 2020-12-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20201203_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRole',
        ),
    ]
