# Generated by Django 3.0.5 on 2020-12-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20201203_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
