# Generated by Django 3.0.5 on 2020-12-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20201204_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
