# Generated by Django 3.0.5 on 2020-12-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20201208_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
