# Generated by Django 3.0.5 on 2020-12-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20201208_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
