# Generated by Django 3.0.5 on 2020-12-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_order_placed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
