# Generated by Django 3.0.5 on 2020-12-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_order_cancelled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
