# Generated by Django 3.1.4 on 2020-12-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_auto_20201209_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='placed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
