# Generated by Django 3.1.4 on 2020-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_tracking_placed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='delayed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
